/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const EffectScope: (typeof import("@vue/composition-api"))["EffectScope"];
  const acceptHMRUpdate: (typeof import("pinia"))["acceptHMRUpdate"];
  const computed: (typeof import("@vue/composition-api"))["computed"];
  const createApp: (typeof import("@vue/composition-api"))["createApp"];
  const createPinia: (typeof import("pinia"))["createPinia"];
  const customRef: (typeof import("@vue/composition-api"))["customRef"];
  const defineAsyncComponent: (typeof import("@vue/composition-api"))["defineAsyncComponent"];
  const defineComponent: (typeof import("@vue/composition-api"))["defineComponent"];
  const defineStore: (typeof import("pinia"))["defineStore"];
  const effectScope: (typeof import("@vue/composition-api"))["effectScope"];
  const getActivePinia: (typeof import("pinia"))["getActivePinia"];
  const getCurrentInstance: (typeof import("@vue/composition-api"))["getCurrentInstance"];
  const getCurrentScope: (typeof import("@vue/composition-api"))["getCurrentScope"];
  const h: (typeof import("@vue/composition-api"))["h"];
  const inject: (typeof import("@vue/composition-api"))["inject"];
  const isProxy: (typeof import("@vue/composition-api"))["isProxy"];
  const isReactive: (typeof import("@vue/composition-api"))["isReactive"];
  const isReadonly: (typeof import("@vue/composition-api"))["isReadonly"];
  const isRef: (typeof import("@vue/composition-api"))["isRef"];
  const mapActions: (typeof import("pinia"))["mapActions"];
  const mapGetters: (typeof import("pinia"))["mapGetters"];
  const mapState: (typeof import("pinia"))["mapState"];
  const mapStores: (typeof import("pinia"))["mapStores"];
  const mapWritableState: (typeof import("pinia"))["mapWritableState"];
  const markRaw: (typeof import("@vue/composition-api"))["markRaw"];
  const nextTick: (typeof import("@vue/composition-api"))["nextTick"];
  const onActivated: (typeof import("@vue/composition-api"))["onActivated"];
  const onBeforeMount: (typeof import("@vue/composition-api"))["onBeforeMount"];
  const onBeforeRouteLeave: (typeof import("vue-router"))["onBeforeRouteLeave"];
  const onBeforeRouteUpdate: (typeof import("vue-router"))["onBeforeRouteUpdate"];
  const onBeforeUnmount: (typeof import("@vue/composition-api"))["onBeforeUnmount"];
  const onBeforeUpdate: (typeof import("@vue/composition-api"))["onBeforeUpdate"];
  const onDeactivated: (typeof import("@vue/composition-api"))["onDeactivated"];
  const onErrorCaptured: (typeof import("@vue/composition-api"))["onErrorCaptured"];
  const onMounted: (typeof import("@vue/composition-api"))["onMounted"];
  const onRenderTracked: (typeof import("vue"))["onRenderTracked"];
  const onRenderTriggered: (typeof import("vue"))["onRenderTriggered"];
  const onScopeDispose: (typeof import("@vue/composition-api"))["onScopeDispose"];
  const onServerPrefetch: (typeof import("@vue/composition-api"))["onServerPrefetch"];
  const onUnmounted: (typeof import("@vue/composition-api"))["onUnmounted"];
  const onUpdated: (typeof import("@vue/composition-api"))["onUpdated"];
  const provide: (typeof import("@vue/composition-api"))["provide"];
  const reactive: (typeof import("@vue/composition-api"))["reactive"];
  const readonly: (typeof import("@vue/composition-api"))["readonly"];
  const ref: (typeof import("@vue/composition-api"))["ref"];
  const resolveComponent: (typeof import("vue"))["resolveComponent"];
  const setActivePinia: (typeof import("pinia"))["setActivePinia"];
  const setMapStoreSuffix: (typeof import("pinia"))["setMapStoreSuffix"];
  const shallowReactive: (typeof import("@vue/composition-api"))["shallowReactive"];
  const shallowReadonly: (typeof import("@vue/composition-api"))["shallowReadonly"];
  const shallowRef: (typeof import("@vue/composition-api"))["shallowRef"];
  const storeToRefs: (typeof import("pinia"))["storeToRefs"];
  const toRaw: (typeof import("@vue/composition-api"))["toRaw"];
  const toRef: (typeof import("@vue/composition-api"))["toRef"];
  const toRefs: (typeof import("@vue/composition-api"))["toRefs"];
  const toValue: (typeof import("@vue/composition-api"))["toValue"];
  const triggerRef: (typeof import("@vue/composition-api"))["triggerRef"];
  const unref: (typeof import("@vue/composition-api"))["unref"];
  const useAttrs: (typeof import("@vue/composition-api"))["useAttrs"];
  const useCssModule: (typeof import("@vue/composition-api"))["useCssModule"];
  const useCssVars: (typeof import("vue"))["useCssVars"];
  const useI18n: (typeof import("vue-i18n"))["useI18n"];
  const useLink: (typeof import("vue-router"))["useLink"];
  const useRoute: (typeof import("vue-router"))["useRoute"];
  const useRouter: (typeof import("vue-router"))["useRouter"];
  const useSlots: (typeof import("@vue/composition-api"))["useSlots"];
  const watch: (typeof import("@vue/composition-api"))["watch"];
  const watchEffect: (typeof import("@vue/composition-api"))["watchEffect"];
  const watchPostEffect: (typeof import("@vue/composition-api"))["watchPostEffect"];
  const watchSyncEffect: (typeof import("@vue/composition-api"))["watchSyncEffect"];
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    ComponentPublicInstance,
    ComputedRef,
    InjectionKey,
    PropType,
    Ref,
    VNode,
  } from "@vue/composition-api";
}
