/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElAside: (typeof import("element-plus/es"))["ElAside"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCol: (typeof import("element-plus/es"))["ElCol"];
    ElContainer: (typeof import("element-plus/es"))["ElContainer"];
    ElFor: (typeof import("element-plus/es"))["ElFor"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElFromItem: (typeof import("element-plus/es"))["ElFromItem"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElMain: (typeof import("element-plus/es"))["ElMain"];
    ElRow: (typeof import("element-plus/es"))["ElRow"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
